openapi: 3.0.0
info:
  title: Products API
  description: A simple CRUD api for products
  version: 0.0.1
paths:

  /products:
    get:
      summary: Returns a list of Products
      responses:
        '200':
          description: A JSON array of Products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                    price:
                      type: float
                      format: float64
                      example: 2.34
                    createdAt:
                      type: datetime
                      example: 2020-01-10T00:00:00Z
                    updatedAt:
                      type: datetime
                      example: 2020-01-10T00:00:00Z
                    deletedAt:
                      type: datetime
                      example: 2020-01-10T00:00:00Z
